### ISSUE TITLE
a question about paper

### ISSUE THREAD

**Issue by coallar** [Yussef93/EdgeSSFewShotMicroscopy#1]
Hi, while reading the paper, I find  that:  ' In practice, we observed that it is not meaningful to completely rely on the same model for cell segmentation and edge prediction '.  I have great interested in this thinking. So, could you share me that: is it suitable for any other segmentation task like Cityscape or ADE20k?  And do you have make a comparison between them? Thanks

**Comment by Yussef93** [comment]
Hi, Thanks for your interest! The concept could be scaled to any other dataset. However, whether it works or not is dependant on the problem at hand. In our case, we tailored the solution for microscopy image cell segmentation.
